### ISSUE TITLE
cjs files are not present in npm package

### ISSUE THREAD

**Issue by Frank3K** [bennypowers/lit-css#4]
The package.json references two `cjs` files (with different file names?):

https://github.com/bennypowers/lit-css/blob/57447c3523fdf4cc9e22922859512c4295e2c2b3/packages/rollup-plugin-lit-css/package.json#L10
https://github.com/bennypowers/lit-css/blob/57447c3523fdf4cc9e22922859512c4295e2c2b3/packages/rollup-plugin-lit-css/package.json#L29

The [npm package of version 3.0.0](https://registry.npmjs.org/rollup-plugin-lit-css/-/rollup-plugin-lit-css-3.0.0.tgz) does not include any of these.

**Comment by bennypowers** [comment]
Fixed in [3.0.1](https://unpkg.com/browse/rollup-plugin-lit-css@3.0.1/)

Thanks!
