### ISSUE TITLE
Replacing uglifycss

### ISSUE THREAD

**Issue by muratcorlu** [bennypowers/lit-css#43]
UglifyCSS [replacing `0px`s to `0`](https://github.com/fmarcia/uglifycss/blob/3a4312ef9a321643ab27cf7438b85c92498af19b/uglifycss-lib.js#L701) without any configuration options. And that causes issues with using `0px` in CSS variables, like defined here: https://www.oddbird.net/2022/08/04/zero-units/

When I check [UglifyCSS repository](https://github.com/fmarcia/uglifycss) I see that it's not maintained for a long time. Can we consider replacing it with a more modern and configurable option like [clean-css](https://github.com/clean-css/clean-css)?

**Comment by bennypowers** [comment]
Fascinating! thanks for the issue. Yes, I'm happy to review a PR that replaces uglify css with clean-css.

In the mean time, you can workaround by setting `uglify: false` and using `transform`
```js
litCssPlugin({
  uglify: false,
  transform: (data, { filePath }) => new CleanCSS().minify(data),
})
```

**Comment by muratcorlu** [comment]
I can try to send a PR for that but it will be a breaking change for the library since config options and outputs will be different starting from that point. Are you ok to publish a major release for that?
