### ISSUE TITLE
Add support for esbuild 0.18.x

### ISSUE THREAD

**Issue by cedx** [bennypowers/lit-css#45]
[esbuild](https://esbuild.github.io) 0.18 has been released (see https://github.com/evanw/esbuild/blob/main/CHANGELOG.md) but `npm` refuses to update my dependencies:

```shell
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @cedx/dummy-project@0.0.0
npm WARN Found: esbuild@0.17.19
npm WARN node_modules/esbuild
npm WARN   dev esbuild@"^0.18.0" from the root project
npm WARN   1 more (esbuild-plugin-minify-html-literals)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer esbuild@"^0.16.17 || ^0.17.16" from esbuild-plugin-minify-html-literals@1.0.4
npm WARN node_modules/esbuild-plugin-minify-html-literals
npm WARN   dev esbuild-plugin-minify-html-literals@"^1.0.4" from the root project
```

Can you check/fix this? Thank you in advance.

**Comment by bennypowers** [comment]
are you able to test it out with `--force`?

**Comment by cedx** [comment]
Yes: using `npm update/install --force` works... and I don't see any visible issue when the app is compiled (i.e. the HTML literals seem fine).

![image](https://github.com/bennypowers/lit-css/assets/1643950/5cfb6f15-13ae-44f6-86f6-5799868598d6)

**Comment by bennypowers** [comment]
give'r https://github.com/bennypowers/lit-css/pull/46
