### ISSUE TITLE
typescript-transform-lit-css : not working with typescript 5.5

### ISSUE THREAD

**Issue by Lookwe69** [bennypowers/lit-css#56]
I don't know if it's a ts-patch bug or typescript-transform-lit-css.
Typescript 5.4 :
imports are transformed with a lit css tag.

Typescript 5.5 :
nothing change,
import styles from './internal/checkbox-styles.css';

**Comment by bennypowers** [comment]
thanks for the issue. with 5.5 out i'm sure I'll be updating my day-job stuff soon enough, and that will likely require investigating further.

Any more information you can provide would be helpful

**Comment by bennypowers** [comment]
This is working for me with 5.6 so i'll close for now.

If you have *a minimal reproduction repo*, please reopen.
