### ISSUE TITLE
Update package.json to allow esbuild > 0.20.x

### ISSUE THREAD

**Issue by thenoseman** [bennypowers/lit-css#57]
Would it be possible to update the `package.json` to allow esbuild versions > 0.20.x?

Currently I have to use an `overrides` like this:

```json
"overrides": {
  "esbuild-plugin-lit-css": {
    "esbuild": "^0.23.0"
  }
}
```

Thanks for this very useful library!

**Comment by bennypowers** [comment]
https://github.com/bennypowers/lit-css/releases/tag/esbuild-plugin-lit-css%403.0.1

**Comment by thenoseman** [comment]
That was fast :) Many thanks!
