### ISSUE TITLE
[esbuild-plugin-lit-css] need esbuild v0.13.4 support

### ISSUE THREAD

**Issue by benjamind** [bennypowers/lit-css#9]
The peer dependency on esbuild v0.12.14 is restricting usage of this plugin with latest esbuild.

Any chance we could get an update?

**Comment by voidus** [comment]
Please also bump for esbuild 0.14

**Comment by bennypowers** [comment]
Happy to take a PR. Should suffice to just specify a range, i'd think? Thanks for the issue.

**Comment by bennypowers** [comment]
released in 1.2.3
